---
image: ruby:2.4

# rubocop:
#   script:
#     - rubocop

pages:
  image: busybox:latest
  script:
    - sed -e "s|// axios.defaults.*;|axios.defaults.baseUrl = '$DASHBOARD_URL'|" -i public/index.html
  artifacts:
    paths:
      - public
